dist: focal
language: c++

stages:
  - build
  - lint

jobs:
  include:
    - stage: lint
      addons:
        apt:
          packages:
            - dos2unix
            - recode
      script:
        - bash ./format.sh
    - stage: build
      addons:
        apt:
          packages:
            - cmake
      script:
        - |
          mkdir -p build
          pushd ./build
          cmake ../
          popd
        - |
          pushd ./build
          cmake --build .
          popd

